project_id = "iqssphbijyzqxeacisis"

[functions.zenopay-topup]
verify_jwt = true

[functions.zenopay-check-status]
verify_jwt = true

[functions.send-password-reset-sms]
verify_jwt = false

[functions.zenopay-subscribe]
verify_jwt = true

[functions.zenopay-check-subscription]
verify_jwt = true
